### ISSUE TITLE
Не указана версия в разделе описания установки

### ISSUE THREAD

**Issue by kasitoru** [Danil005/php-yandex-alisa#2]
Из за чего composer ругается:

>   [InvalidArgumentException]                                                   
>   Could not find a version of package danil005/php-yandex-alisa matching your  
>    minimum-stability (stable). Require it with an explicit version constraint  
>    allowing its desired stability.   

Вот правильный вариант:

> composer require danil005/php-yandex-alisa:dev-master

**Comment by Danil005** [comment]
Исправил, спасибо.
